//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_EMPLE
    {
        public string email { get; set; }
        public string nombre { get; set; }
        public string codven { get; set; }
        public string codsuc { get; set; }
        public string funcionp { get; set; }
        public string funcions { get; set; }
        public bool inactivo { get; set; }
    }
}
